// Code generated by qtc from "article.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line server/src/meguca/templates/article.qtpl:1
package templates

//line server/src/meguca/templates/article.qtpl:1
import "fmt"

//line server/src/meguca/templates/article.qtpl:2
import "strconv"

//line server/src/meguca/templates/article.qtpl:3
import "meguca/common"

//line server/src/meguca/templates/article.qtpl:4
import "meguca/lang"

//line server/src/meguca/templates/article.qtpl:5
import "meguca/imager/assets"

//line server/src/meguca/templates/article.qtpl:6
import "meguca/util"

//line server/src/meguca/templates/article.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line server/src/meguca/templates/article.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line server/src/meguca/templates/article.qtpl:8
func streamrenderArticle(qw422016 *qt422016.Writer, p common.Post, c articleContext) {
	//line server/src/meguca/templates/article.qtpl:9
	id := strconv.FormatUint(p.ID, 10)

	//line server/src/meguca/templates/article.qtpl:10
	ln := lang.Get()

	//line server/src/meguca/templates/article.qtpl:10
	qw422016.N().S(`<article id="p`)
	//line server/src/meguca/templates/article.qtpl:11
	qw422016.N().S(id)
	//line server/src/meguca/templates/article.qtpl:11
	qw422016.N().S(`"`)
	//line server/src/meguca/templates/article.qtpl:11
	qw422016.N().S(` `)
	//line server/src/meguca/templates/article.qtpl:11
	streampostClass(qw422016, p, c.op)
	//line server/src/meguca/templates/article.qtpl:11
	qw422016.N().S(`>`)
	//line server/src/meguca/templates/article.qtpl:12
	streamdeletedToggle(qw422016)
	//line server/src/meguca/templates/article.qtpl:12
	qw422016.N().S(`<header class="spaced"><input type="checkbox" class="mod-checkbox hidden">`)
	//line server/src/meguca/templates/article.qtpl:15
	streamrenderSticky(qw422016, c.sticky)
	//line server/src/meguca/templates/article.qtpl:16
	streamrenderLocked(qw422016, c.locked)
	//line server/src/meguca/templates/article.qtpl:17
	if c.subject != "" {
		//line server/src/meguca/templates/article.qtpl:18
		if c.board != "" {
			//line server/src/meguca/templates/article.qtpl:18
			qw422016.N().S(`<b class="board">/`)
			//line server/src/meguca/templates/article.qtpl:20
			qw422016.N().S(c.board)
			//line server/src/meguca/templates/article.qtpl:20
			qw422016.N().S(`/</b>`)
			//line server/src/meguca/templates/article.qtpl:22
		}
		//line server/src/meguca/templates/article.qtpl:22
		qw422016.N().S(`<h3>「`)
		//line server/src/meguca/templates/article.qtpl:24
		qw422016.E().S(c.subject)
		//line server/src/meguca/templates/article.qtpl:24
		qw422016.N().S(`」</h3>`)
		//line server/src/meguca/templates/article.qtpl:26
	}
	//line server/src/meguca/templates/article.qtpl:26
	qw422016.N().S(`<b class="name spaced`)
	//line server/src/meguca/templates/article.qtpl:27
	if p.Auth != "" {
		//line server/src/meguca/templates/article.qtpl:27
		qw422016.N().S(` `)
		//line server/src/meguca/templates/article.qtpl:27
		qw422016.N().S(`admin`)
		//line server/src/meguca/templates/article.qtpl:27
	}
	//line server/src/meguca/templates/article.qtpl:27
	if p.Sage {
		//line server/src/meguca/templates/article.qtpl:27
		qw422016.N().S(` `)
		//line server/src/meguca/templates/article.qtpl:27
		qw422016.N().S(`sage`)
		//line server/src/meguca/templates/article.qtpl:27
	}
	//line server/src/meguca/templates/article.qtpl:27
	qw422016.N().S(`">`)
	//line server/src/meguca/templates/article.qtpl:28
	if p.Name != "" || p.Trip == "" {
		//line server/src/meguca/templates/article.qtpl:28
		qw422016.N().S(`<span>`)
		//line server/src/meguca/templates/article.qtpl:30
		if p.Name != "" {
			//line server/src/meguca/templates/article.qtpl:31
			qw422016.E().S(p.Name)
			//line server/src/meguca/templates/article.qtpl:32
		} else {
			//line server/src/meguca/templates/article.qtpl:33
			qw422016.N().S(ln.Common.Posts["anon"])
			//line server/src/meguca/templates/article.qtpl:34
		}
		//line server/src/meguca/templates/article.qtpl:34
		qw422016.N().S(`</span>`)
		//line server/src/meguca/templates/article.qtpl:36
	}
	//line server/src/meguca/templates/article.qtpl:37
	if p.Trip != "" {
		//line server/src/meguca/templates/article.qtpl:37
		qw422016.N().S(`<code>!`)
		//line server/src/meguca/templates/article.qtpl:39
		qw422016.E().S(p.Trip)
		//line server/src/meguca/templates/article.qtpl:39
		qw422016.N().S(`</code>`)
		//line server/src/meguca/templates/article.qtpl:41
	}
	//line server/src/meguca/templates/article.qtpl:42
	if p.PosterID != "" {
		//line server/src/meguca/templates/article.qtpl:42
		qw422016.N().S(`<span>(`)
		//line server/src/meguca/templates/article.qtpl:44
		qw422016.E().S(p.PosterID)
		//line server/src/meguca/templates/article.qtpl:44
		qw422016.N().S(`)</span>`)
		//line server/src/meguca/templates/article.qtpl:46
	}
	//line server/src/meguca/templates/article.qtpl:47
	if p.Auth != "" {
		//line server/src/meguca/templates/article.qtpl:47
		qw422016.N().S(`<span>##`)
		//line server/src/meguca/templates/article.qtpl:49
		qw422016.N().S(` `)
		//line server/src/meguca/templates/article.qtpl:49
		qw422016.N().S(ln.Common.Posts[p.Auth])
		//line server/src/meguca/templates/article.qtpl:49
		qw422016.N().S(`</span>`)
		//line server/src/meguca/templates/article.qtpl:51
	}
	//line server/src/meguca/templates/article.qtpl:51
	qw422016.N().S(`</b>`)
	//line server/src/meguca/templates/article.qtpl:53
	if p.Flag != "" {
		//line server/src/meguca/templates/article.qtpl:54
		title, ok := countryMap[p.Flag]

		//line server/src/meguca/templates/article.qtpl:55
		if !ok {
			//line server/src/meguca/templates/article.qtpl:56
			title = p.Flag

			//line server/src/meguca/templates/article.qtpl:57
		}
		//line server/src/meguca/templates/article.qtpl:57
		qw422016.N().S(`<img class="flag" src="/assets/flags/`)
		//line server/src/meguca/templates/article.qtpl:58
		qw422016.N().S(p.Flag)
		//line server/src/meguca/templates/article.qtpl:58
		qw422016.N().S(`.svg" title="`)
		//line server/src/meguca/templates/article.qtpl:58
		qw422016.N().S(title)
		//line server/src/meguca/templates/article.qtpl:58
		qw422016.N().S(`">`)
		//line server/src/meguca/templates/article.qtpl:59
	}
	//line server/src/meguca/templates/article.qtpl:59
	qw422016.N().S(`<time>`)
	//line server/src/meguca/templates/article.qtpl:61
	qw422016.N().S(formatTime(p.Time))
	//line server/src/meguca/templates/article.qtpl:61
	qw422016.N().S(`</time><nav>`)
	//line server/src/meguca/templates/article.qtpl:64
	url := "#p" + id

	//line server/src/meguca/templates/article.qtpl:65
	if c.index {
		//line server/src/meguca/templates/article.qtpl:66
		url = util.ConcatStrings("/all/", id, "?last=100", url)

		//line server/src/meguca/templates/article.qtpl:67
	}
	//line server/src/meguca/templates/article.qtpl:67
	qw422016.N().S(`<a href="`)
	//line server/src/meguca/templates/article.qtpl:68
	qw422016.N().S(url)
	//line server/src/meguca/templates/article.qtpl:68
	qw422016.N().S(`">No.</a><a class="quote" href="`)
	//line server/src/meguca/templates/article.qtpl:71
	qw422016.N().S(url)
	//line server/src/meguca/templates/article.qtpl:71
	qw422016.N().S(`">`)
	//line server/src/meguca/templates/article.qtpl:72
	qw422016.N().S(id)
	//line server/src/meguca/templates/article.qtpl:72
	qw422016.N().S(`</a></nav>`)
	//line server/src/meguca/templates/article.qtpl:75
	if c.index && c.subject != "" {
		//line server/src/meguca/templates/article.qtpl:75
		qw422016.N().S(`<span>`)
		//line server/src/meguca/templates/article.qtpl:77
		streamexpandLink(qw422016, "all", id)
		//line server/src/meguca/templates/article.qtpl:78
		streamlast100Link(qw422016, "all", id)
		//line server/src/meguca/templates/article.qtpl:78
		qw422016.N().S(`</span>`)
		//line server/src/meguca/templates/article.qtpl:80
	}
	//line server/src/meguca/templates/article.qtpl:81
	streamcontrolLink(qw422016)
	//line server/src/meguca/templates/article.qtpl:82
	if c.op == p.ID {
		//line server/src/meguca/templates/article.qtpl:83
		streamthreadWatcherToggle(qw422016, p.ID)
		//line server/src/meguca/templates/article.qtpl:84
	}
	//line server/src/meguca/templates/article.qtpl:84
	qw422016.N().S(`</header>`)
	//line server/src/meguca/templates/article.qtpl:86
	var src string

	//line server/src/meguca/templates/article.qtpl:87
	if p.Image != nil {
		//line server/src/meguca/templates/article.qtpl:88
		img := *p.Image

		//line server/src/meguca/templates/article.qtpl:89
		src = assets.SourcePath(img.FileType, img.SHA1)

		//line server/src/meguca/templates/article.qtpl:89
		qw422016.N().S(`<figcaption class="spaced"><a class="image-toggle act" hidden></a><span class="spaced image-search-container">`)
		//line server/src/meguca/templates/article.qtpl:93
		streamimageSearch(qw422016, c.root, img)
		//line server/src/meguca/templates/article.qtpl:93
		qw422016.N().S(`</span><span class="fileinfo">`)
		//line server/src/meguca/templates/article.qtpl:96
		if img.Artist != "" {
			//line server/src/meguca/templates/article.qtpl:96
			qw422016.N().S(`<span class="media-artist">`)
			//line server/src/meguca/templates/article.qtpl:98
			qw422016.E().S(img.Artist)
			//line server/src/meguca/templates/article.qtpl:98
			qw422016.N().S(`</span>`)
			//line server/src/meguca/templates/article.qtpl:100
		}
		//line server/src/meguca/templates/article.qtpl:101
		if img.Title != "" {
			//line server/src/meguca/templates/article.qtpl:101
			qw422016.N().S(`<span class="media-title">`)
			//line server/src/meguca/templates/article.qtpl:103
			qw422016.E().S(img.Title)
			//line server/src/meguca/templates/article.qtpl:103
			qw422016.N().S(`</span>`)
			//line server/src/meguca/templates/article.qtpl:105
		}
		//line server/src/meguca/templates/article.qtpl:106
		if img.Audio {
			//line server/src/meguca/templates/article.qtpl:106
			qw422016.N().S(`<span class="has-audio">♫</span>`)
			//line server/src/meguca/templates/article.qtpl:110
		}
		//line server/src/meguca/templates/article.qtpl:111
		if img.Length != 0 {
			//line server/src/meguca/templates/article.qtpl:111
			qw422016.N().S(`<span class="media-length">`)
			//line server/src/meguca/templates/article.qtpl:113
			l := img.Length

			//line server/src/meguca/templates/article.qtpl:114
			if l < 60 {
				//line server/src/meguca/templates/article.qtpl:115
				qw422016.N().S(fmt.Sprintf("0:%02d", l))
				//line server/src/meguca/templates/article.qtpl:116
			} else {
				//line server/src/meguca/templates/article.qtpl:117
				min := l / 60

				//line server/src/meguca/templates/article.qtpl:118
				qw422016.N().S(fmt.Sprintf("%02d:%02d", min, l-min*60))
				//line server/src/meguca/templates/article.qtpl:119
			}
			//line server/src/meguca/templates/article.qtpl:119
			qw422016.N().S(`</span>`)
			//line server/src/meguca/templates/article.qtpl:121
		}
		//line server/src/meguca/templates/article.qtpl:122
		if img.APNG {
			//line server/src/meguca/templates/article.qtpl:122
			qw422016.N().S(`<span class="is-apng">APNG</span>`)
			//line server/src/meguca/templates/article.qtpl:126
		}
		//line server/src/meguca/templates/article.qtpl:126
		qw422016.N().S(`<span class="filesize">`)
		//line server/src/meguca/templates/article.qtpl:128
		qw422016.N().S(readableFileSize(img.Size))
		//line server/src/meguca/templates/article.qtpl:128
		qw422016.N().S(`</span>`)
		//line server/src/meguca/templates/article.qtpl:130
		if img.Dims != [4]uint16{} {
			//line server/src/meguca/templates/article.qtpl:130
			qw422016.N().S(`<span class="dims">`)
			//line server/src/meguca/templates/article.qtpl:132
			qw422016.N().S(strconv.FormatUint(uint64(img.Dims[0]), 10))
			//line server/src/meguca/templates/article.qtpl:132
			qw422016.N().S(`x`)
			//line server/src/meguca/templates/article.qtpl:134
			qw422016.N().S(strconv.FormatUint(uint64(img.Dims[1]), 10))
			//line server/src/meguca/templates/article.qtpl:134
			qw422016.N().S(`</span>`)
			//line server/src/meguca/templates/article.qtpl:136
		}
		//line server/src/meguca/templates/article.qtpl:136
		qw422016.N().S(`</span>`)
		//line server/src/meguca/templates/article.qtpl:138
		name := imageName(img.FileType, img.Name)

		//line server/src/meguca/templates/article.qtpl:138
		qw422016.N().S(`<a href="`)
		//line server/src/meguca/templates/article.qtpl:139
		qw422016.N().S(assets.RelativeSourcePath(img.FileType, img.SHA1))
		//line server/src/meguca/templates/article.qtpl:139
		qw422016.N().S(`" download="`)
		//line server/src/meguca/templates/article.qtpl:139
		qw422016.N().S(name)
		//line server/src/meguca/templates/article.qtpl:139
		qw422016.N().S(`">`)
		//line server/src/meguca/templates/article.qtpl:140
		qw422016.N().S(name)
		//line server/src/meguca/templates/article.qtpl:140
		qw422016.N().S(`</a></figcaption>`)
		//line server/src/meguca/templates/article.qtpl:143
	}
	//line server/src/meguca/templates/article.qtpl:143
	qw422016.N().S(`<div class="post-container">`)
	//line server/src/meguca/templates/article.qtpl:145
	if p.Image != nil {
		//line server/src/meguca/templates/article.qtpl:146
		img := *p.Image

		//line server/src/meguca/templates/article.qtpl:146
		qw422016.N().S(`<figure><a target="_blank" href="`)
		//line server/src/meguca/templates/article.qtpl:148
		qw422016.N().S(src)
		//line server/src/meguca/templates/article.qtpl:148
		qw422016.N().S(`">`)
		//line server/src/meguca/templates/article.qtpl:149
		switch {
		//line server/src/meguca/templates/article.qtpl:150
		case img.ThumbType == common.NoFile:
			//line server/src/meguca/templates/article.qtpl:151
			var file string

			//line server/src/meguca/templates/article.qtpl:152
			switch img.FileType {
			//line server/src/meguca/templates/article.qtpl:153
			case common.MP4, common.MP3, common.OGG, common.FLAC:
				//line server/src/meguca/templates/article.qtpl:154
				file = "audio"

			//line server/src/meguca/templates/article.qtpl:155
			default:
				//line server/src/meguca/templates/article.qtpl:156
				file = "file"

				//line server/src/meguca/templates/article.qtpl:157
			}
			//line server/src/meguca/templates/article.qtpl:157
			qw422016.N().S(`<img src="/assets/`)
			//line server/src/meguca/templates/article.qtpl:158
			qw422016.N().S(file)
			//line server/src/meguca/templates/article.qtpl:158
			qw422016.N().S(`.png" width="150" height="150">`)
		//line server/src/meguca/templates/article.qtpl:159
		case img.Spoiler:
			//line server/src/meguca/templates/article.qtpl:162
			qw422016.N().S(`<img src="/assets/spoil/default.jpg" width="150" height="150">`)
		//line server/src/meguca/templates/article.qtpl:164
		default:
			//line server/src/meguca/templates/article.qtpl:164
			qw422016.N().S(`<img src="`)
			//line server/src/meguca/templates/article.qtpl:165
			qw422016.N().S(assets.ThumbPath(img.ThumbType, img.SHA1))
			//line server/src/meguca/templates/article.qtpl:165
			qw422016.N().S(`" width="`)
			//line server/src/meguca/templates/article.qtpl:165
			qw422016.N().D(int(img.Dims[2]))
			//line server/src/meguca/templates/article.qtpl:165
			qw422016.N().S(`" height="`)
			//line server/src/meguca/templates/article.qtpl:165
			qw422016.N().D(int(img.Dims[3]))
			//line server/src/meguca/templates/article.qtpl:165
			qw422016.N().S(`">`)
			//line server/src/meguca/templates/article.qtpl:166
		}
		//line server/src/meguca/templates/article.qtpl:166
		qw422016.N().S(`</a></figure>`)
		//line server/src/meguca/templates/article.qtpl:169
	}
	//line server/src/meguca/templates/article.qtpl:169
	qw422016.N().S(`<blockquote>`)
	//line server/src/meguca/templates/article.qtpl:171
	streambody(qw422016, p, c.op, c.board, c.index, c.rbText, c.pyu)
	//line server/src/meguca/templates/article.qtpl:171
	qw422016.N().S(`</blockquote>`)
	//line server/src/meguca/templates/article.qtpl:173
	for _, e := range p.Moderation {
		//line server/src/meguca/templates/article.qtpl:173
		qw422016.N().S(`<b class="admin post-moderation">`)
		//line server/src/meguca/templates/article.qtpl:175
		streampostModeration(qw422016, e)
		//line server/src/meguca/templates/article.qtpl:175
		qw422016.N().S(`<br></b>`)
		//line server/src/meguca/templates/article.qtpl:178
	}
	//line server/src/meguca/templates/article.qtpl:178
	qw422016.N().S(`</div>`)
	//line server/src/meguca/templates/article.qtpl:180
	if c.omit != 0 {
		//line server/src/meguca/templates/article.qtpl:180
		qw422016.N().S(`<span class="omit" data-omit="`)
		//line server/src/meguca/templates/article.qtpl:181
		qw422016.N().D(c.omit)
		//line server/src/meguca/templates/article.qtpl:181
		qw422016.N().S(`" data-image-omit="`)
		//line server/src/meguca/templates/article.qtpl:181
		qw422016.N().D(c.imageOmit)
		//line server/src/meguca/templates/article.qtpl:181
		qw422016.N().S(`">`)
		//line server/src/meguca/templates/article.qtpl:182
		qw422016.N().S(pluralize(c.omit, "post"))
		//line server/src/meguca/templates/article.qtpl:183
		qw422016.N().S(` `)
		//line server/src/meguca/templates/article.qtpl:183
		qw422016.N().S(ln.Common.Posts["and"])
		//line server/src/meguca/templates/article.qtpl:183
		qw422016.N().S(` `)
		//line server/src/meguca/templates/article.qtpl:184
		qw422016.N().S(pluralize(c.imageOmit, "image"))
		//line server/src/meguca/templates/article.qtpl:185
		qw422016.N().S(` `)
		//line server/src/meguca/templates/article.qtpl:185
		qw422016.N().S(`omitted`)
		//line server/src/meguca/templates/article.qtpl:185
		qw422016.N().S(` `)
		//line server/src/meguca/templates/article.qtpl:185
		qw422016.N().S(`<span class="act"><a href="`)
		//line server/src/meguca/templates/article.qtpl:187
		qw422016.N().S(strconv.FormatUint(c.op, 10))
		//line server/src/meguca/templates/article.qtpl:187
		qw422016.N().S(`">`)
		//line server/src/meguca/templates/article.qtpl:188
		qw422016.N().S(ln.Common.Posts["seeAll"])
		//line server/src/meguca/templates/article.qtpl:188
		qw422016.N().S(`</a></span></span>`)
		//line server/src/meguca/templates/article.qtpl:192
	}
	//line server/src/meguca/templates/article.qtpl:193
	if bls := c.backlinks[p.ID]; len(bls) != 0 {
		//line server/src/meguca/templates/article.qtpl:193
		qw422016.N().S(`<span class="backlinks spaced">`)
		//line server/src/meguca/templates/article.qtpl:195
		for _, l := range bls {
			//line server/src/meguca/templates/article.qtpl:195
			qw422016.N().S(`<em>`)
			//line server/src/meguca/templates/article.qtpl:197
			streampostLink(qw422016, l, c.index || l.OP != c.op, c.index)
			//line server/src/meguca/templates/article.qtpl:197
			qw422016.N().S(`</em>`)
			//line server/src/meguca/templates/article.qtpl:199
		}
		//line server/src/meguca/templates/article.qtpl:199
		qw422016.N().S(`</span>`)
		//line server/src/meguca/templates/article.qtpl:201
	}
	//line server/src/meguca/templates/article.qtpl:201
	qw422016.N().S(`</article>`)
//line server/src/meguca/templates/article.qtpl:203
}

//line server/src/meguca/templates/article.qtpl:203
func writerenderArticle(qq422016 qtio422016.Writer, p common.Post, c articleContext) {
	//line server/src/meguca/templates/article.qtpl:203
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line server/src/meguca/templates/article.qtpl:203
	streamrenderArticle(qw422016, p, c)
	//line server/src/meguca/templates/article.qtpl:203
	qt422016.ReleaseWriter(qw422016)
//line server/src/meguca/templates/article.qtpl:203
}

//line server/src/meguca/templates/article.qtpl:203
func renderArticle(p common.Post, c articleContext) string {
	//line server/src/meguca/templates/article.qtpl:203
	qb422016 := qt422016.AcquireByteBuffer()
	//line server/src/meguca/templates/article.qtpl:203
	writerenderArticle(qb422016, p, c)
	//line server/src/meguca/templates/article.qtpl:203
	qs422016 := string(qb422016.B)
	//line server/src/meguca/templates/article.qtpl:203
	qt422016.ReleaseByteBuffer(qb422016)
	//line server/src/meguca/templates/article.qtpl:203
	return qs422016
//line server/src/meguca/templates/article.qtpl:203
}

// Render image search links according to file type

//line server/src/meguca/templates/article.qtpl:206
func streamimageSearch(qw422016 *qt422016.Writer, root string, img common.Image) {
	//line server/src/meguca/templates/article.qtpl:207
	if img.ThumbType == common.NoFile || img.FileType == common.PDF {
		//line server/src/meguca/templates/article.qtpl:208
		return
		//line server/src/meguca/templates/article.qtpl:209
	}
	//line server/src/meguca/templates/article.qtpl:211
	url := root + assets.ImageSearchPath(img.ImageCommon)

	//line server/src/meguca/templates/article.qtpl:211
	qw422016.N().S(`<a class="image-search google" target="_blank" rel="nofollow" href="https://www.google.com/searchbyimage?image_url=`)
	//line server/src/meguca/templates/article.qtpl:212
	qw422016.N().S(url)
	//line server/src/meguca/templates/article.qtpl:212
	qw422016.N().S(`">G</a><a class="image-search iqdb" target="_blank" rel="nofollow" href="http://iqdb.org/?url=`)
	//line server/src/meguca/templates/article.qtpl:215
	qw422016.N().S(url)
	//line server/src/meguca/templates/article.qtpl:215
	qw422016.N().S(`">Iq</a><a class="image-search saucenao" target="_blank" rel="nofollow" href="http://saucenao.com/search.php?db=999&url=`)
	//line server/src/meguca/templates/article.qtpl:218
	qw422016.N().S(url)
	//line server/src/meguca/templates/article.qtpl:218
	qw422016.N().S(`">Sn</a><a class="image-search whatAnime" target="_blank" rel="nofollow" href="https://trace.moe/?url=`)
	//line server/src/meguca/templates/article.qtpl:221
	qw422016.N().S(url)
	//line server/src/meguca/templates/article.qtpl:221
	qw422016.N().S(`">Wa</a>`)
	//line server/src/meguca/templates/article.qtpl:224
	switch img.FileType {
	//line server/src/meguca/templates/article.qtpl:225
	case common.JPEG, common.PNG, common.GIF, common.WEBM:
		//line server/src/meguca/templates/article.qtpl:225
		qw422016.N().S(`<a class="image-search desustorage" target="_blank" rel="nofollow" href="https://desuarchive.org/_/search/image/`)
		//line server/src/meguca/templates/article.qtpl:226
		qw422016.N().S(img.MD5)
		//line server/src/meguca/templates/article.qtpl:226
		qw422016.N().S(`">Ds</a>`)
		//line server/src/meguca/templates/article.qtpl:229
	}
	//line server/src/meguca/templates/article.qtpl:230
	switch img.FileType {
	//line server/src/meguca/templates/article.qtpl:231
	case common.JPEG, common.PNG:
		//line server/src/meguca/templates/article.qtpl:231
		qw422016.N().S(`<a class="image-search exhentai" target="_blank" rel="nofollow" href="http://exhentai.org/?fs_similar=1&fs_exp=1&f_shash=`)
		//line server/src/meguca/templates/article.qtpl:232
		qw422016.N().S(img.SHA1)
		//line server/src/meguca/templates/article.qtpl:232
		qw422016.N().S(`">Ex</a>`)
		//line server/src/meguca/templates/article.qtpl:235
	}
//line server/src/meguca/templates/article.qtpl:236
}

//line server/src/meguca/templates/article.qtpl:236
func writeimageSearch(qq422016 qtio422016.Writer, root string, img common.Image) {
	//line server/src/meguca/templates/article.qtpl:236
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line server/src/meguca/templates/article.qtpl:236
	streamimageSearch(qw422016, root, img)
	//line server/src/meguca/templates/article.qtpl:236
	qt422016.ReleaseWriter(qw422016)
//line server/src/meguca/templates/article.qtpl:236
}

//line server/src/meguca/templates/article.qtpl:236
func imageSearch(root string, img common.Image) string {
	//line server/src/meguca/templates/article.qtpl:236
	qb422016 := qt422016.AcquireByteBuffer()
	//line server/src/meguca/templates/article.qtpl:236
	writeimageSearch(qb422016, root, img)
	//line server/src/meguca/templates/article.qtpl:236
	qs422016 := string(qb422016.B)
	//line server/src/meguca/templates/article.qtpl:236
	qt422016.ReleaseByteBuffer(qb422016)
	//line server/src/meguca/templates/article.qtpl:236
	return qs422016
//line server/src/meguca/templates/article.qtpl:236
}
