// Code generated by qtc from "genericError.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// DefaultError renders any gneral error not specially handled elsewhere

//line server/src/meguca/templates/genericError.qtpl:2
package templates

//line server/src/meguca/templates/genericError.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line server/src/meguca/templates/genericError.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line server/src/meguca/templates/genericError.qtpl:2
func StreamDefaultError(qw422016 *qt422016.Writer, code int, errmsg string) {
	//line server/src/meguca/templates/genericError.qtpl:2
	qw422016.N().S(`<!DOCTYPE html><html><head><meta charset="utf-8"/><link rel="stylesheet" href="/assets/css/error.css"></head><body><p>`)
	//line server/src/meguca/templates/genericError.qtpl:11
	qw422016.N().D(code)
	//line server/src/meguca/templates/genericError.qtpl:11
	qw422016.N().S(` Error: `)
	//line server/src/meguca/templates/genericError.qtpl:11
	qw422016.E().S(errmsg)
	//line server/src/meguca/templates/genericError.qtpl:11
	qw422016.N().S(`</p></body></html>`)
//line server/src/meguca/templates/genericError.qtpl:15
}

//line server/src/meguca/templates/genericError.qtpl:15
func WriteDefaultError(qq422016 qtio422016.Writer, code int, errmsg string) {
	//line server/src/meguca/templates/genericError.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line server/src/meguca/templates/genericError.qtpl:15
	StreamDefaultError(qw422016, code, errmsg)
	//line server/src/meguca/templates/genericError.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line server/src/meguca/templates/genericError.qtpl:15
}

//line server/src/meguca/templates/genericError.qtpl:15
func DefaultError(code int, errmsg string) string {
	//line server/src/meguca/templates/genericError.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line server/src/meguca/templates/genericError.qtpl:15
	WriteDefaultError(qb422016, code, errmsg)
	//line server/src/meguca/templates/genericError.qtpl:15
	qs422016 := string(qb422016.B)
	//line server/src/meguca/templates/genericError.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line server/src/meguca/templates/genericError.qtpl:15
	return qs422016
//line server/src/meguca/templates/genericError.qtpl:15
}
